promote:
   group1: #Group to be promoted from
       to: group2 #Group to be promote to
       minutesreq: 5 #After x minutes of gameplay time
   group2: #Group to be promoted from
       to: group3 #Group to be promote to
       minutesreq: 20 #After x minutes of gameplay time