#true for MySQL and false for SQLite
useMySQL: false

#MySql databse information, if useMySQL is set to true
mysql:
  username: 'mysql_username'
  port: 3306
  password: 'mysql_password'
  host: 'mysql_host'
  database: 'mysql_database'

#Integrate Essentials AFK (default: false)
essentialsAfk: false

#Integrate RoyalCommands AFK (default: false)
rcmdsAfk: false

#Debug mode. If you don't know what you're doing, leave it false (default: false)
debugMode: false

#How often, in minutes, does the server check for promotions (default: 5)
checkPeriod: 5

#Delete players from the database who haven't logged in the set amoutn of days. Set 0 to disable.
purgeAfter: 0

#Default group for new players
defaultGroup: default

#If groups are set-up per world. Eg. in world "creative" the player is in group "moderator", 
#but in world "survival" player is in group "user"
#Only enable this if your permission plugin supports per-world groups.
#Notice: If you enable this, the plugin will use perworld.yml
#so you'll need to set up rank promotions in that file instead of this
#(default: false)
worldSpecificGroups: false

#Promotions list
promote:

   #Group to be promoted from
   group1: 
       #Group to be promoted to
       to: group2
       
       #After specified amount of time played. Usage: d - for days, h - for hours, m - for minutes; 
       #use spaces between days, hours and minutes
       timeReq: 1h 2m

   group2:
       to: group3
       timeReq: 2d 3h