name: TimedRanker
main: ro.raizen.src.timedranker.TimedRanker
version: 1.4.1
description: Promotes players based on total online time.
commands:
    tranker:
       description: TimedRanker main command
permissions:
    tranker.*:
        description: Gives access to all /tranker commands
        children:
            tranker.playtime: true
            tranker.playtime.others: true
            tranker.settime: true
            tranker.addtime: true
            tranker.top: true
            tranker.left: true
            tranker.left.others: true
            tranker.delete: true
            tranker.convert: true
            tranker.purge: true
            tranker.reload: true
        default: op
    tranker.playtime:
        description: Can use /tranker playtime
        default: true
    tranker.playtime.others:
        description: Can use /tranker playtime <player>
        children:
            tranker.playtime: true
        default: op
    tranker.top:
        description: Can use /tranker top
        default: true
    tranker.left:
        description: Can use /tranker left
        default: true
    tranker.left.others:
        description: Can use /tranker left <player> [world]
        children:
            tranker.left: true
        default: true
    tranker.settime:
        description: Can use /tranker settime <player> <minutes>
        default: op
    tranker.addtime:
        description: Can use /tranker addtime <player> <minutes>
        default: op
    tranker.delete:
        description: Can use /tranker delete <player>
        default: op
    tranker.convert:
        description: Can use /tranker convert
        default: op
    tranker.purge:
        description: Can use /tranker purge
        default: op        
    tranker.reload:
        description: Can use /tranker reload
        default: op