name: TimedRanker
main: ro.raizen.src.timedranker.TimedRanker
version: 1.3
description: Promotes players based on total online time.
commands:
    tranker:
       description: TimedRanker main command
permissions:
    tranker.*:
        description: Gives access to all /tranker commands
        children:
            tranker.playtime.*: true
            tranker.settime: true
            tranker.top: true
            tranker.purge: true
            tranker.reload: true
        default: op
    tranker.playtime.*:
        description: Can use /tranker playtime [player]
        children:
            tranker.playtime.me: true
            tranker.playtime.others: true
    tranker.playtime.me:
        description: Can use /tranker playtime
        default: true
    tranker.top:
        description: Can use /tranker top
        default: true
    tranker.left:
        description: Can use /tranker left
        default: true
    tranker.playtime.others:
        description: Can use /tranker <player>
        default: op
    tranker.settime:
        description: Can use /tranker settime <player> <minutes>
        default: op
    tranker.purge:
        description: Can use /tranker purge
        default: op        
    tranker.reload:
        description: Can use /tranker reload
        default: op